package dev.abgleich.bootstrap;

import static org.assertj.core.api.Assertions.assertThat;

import dev.abgleich.application.port.in.ExampleDataUseCase;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Files plus invoices in, reconciliation out: the whole example through parsers, database and every rule
 * is compared with a reviewed text file. A change in behaviour shows up as a readable diff.
 *
 * <p>After an intended change: {@code ./gradlew :bootstrap:test --tests '*GoldenFileTest' -Pgolden.update=true},
 * then review the diff of {@code src/test/resources/golden/example-reconciliation.txt} before committing it.
 */
@AbgleichIntegrationTest
class GoldenFileTest {

    private static final String GOLDEN = "golden/example-reconciliation.txt";

    @Autowired
    ExampleDataUseCase examples;

    @Autowired
    JdbcTemplate jdbc;

    @BeforeEach
    void emptyDatabase() {
        jdbc.execute("truncate allocation, bank_transaction, invoice, statement_import");
    }

    @Test
    void example_reconciliation_matches_the_golden_file() throws IOException {
        examples.load();

        String actual = render();

        if (Boolean.getBoolean("golden.update")) {
            Path file = Path.of("src/test/resources", GOLDEN);
            Files.createDirectories(file.getParent());
            Files.writeString(file, actual, StandardCharsets.UTF_8);
            return;
        }
        Path actualCopy = Path.of("build/golden/example-reconciliation.actual.txt");
        Files.createDirectories(actualCopy.getParent());
        Files.writeString(actualCopy, actual, StandardCharsets.UTF_8);
        assertThat(actual).as("differs from %s; see %s", GOLDEN, actualCopy).isEqualTo(golden());
    }

    private String render() {
        StringBuilder out = new StringBuilder("# Example reconciliation. Synthetic data only.\n");
        out.append("# Generated by GoldenFileTest; review every change of this file.\n\n## Payments\n");
        jdbc.query("""
                select right(t.account_iban, 4) as account, t.booking_date, t.direction, t.amount, t.currency,
                       coalesce(t.counterparty_name, '-') as payer, coalesce(t.remittance_text, '-') as text,
                       coalesce(t.reference, '-') as reference, t.status,
                       coalesce(string_agg(i.invoice_number || ' ' || a.rule || ' ' || a.status
                                           || case when a.charges_written_off > 0
                                                   then ' charges ' || a.charges_written_off else '' end,
                                           ', ' order by i.invoice_number, a.status), '-') as allocations
                  from bank_transaction t
                  left join allocation a on a.transaction_id = t.id
                  left join invoice i on i.id = a.invoice_id
                 group by t.id
                 order by t.account_iban, t.booking_date, t.dedup_key
                """, rs -> {
            out.append(String.format("%s %s %-6s %s %10s | %s | %s | %s | %s -> %s%n",
                    rs.getString("account"), rs.getDate("booking_date").toLocalDate(), rs.getString("direction"),
                    rs.getString("currency"), rs.getBigDecimal("amount").toPlainString(), rs.getString("payer"),
                    rs.getString("text"), rs.getString("reference"), rs.getString("status"),
                    rs.getString("allocations")));
        });
        out.append("\n## Invoices\n");
        jdbc.query("select invoice_number, status, amount, paid_amount, currency from invoice order by invoice_number",
                rs -> {
                    out.append(String.format("%-13s %-15s %s %10s paid %10s%n", rs.getString("invoice_number"),
                            rs.getString("status"), rs.getString("currency"), rs.getBigDecimal("amount").toPlainString(),
                            rs.getBigDecimal("paid_amount").toPlainString()));
                });
        return out.toString();
    }

    private static String golden() throws IOException {
        try (InputStream in = GoldenFileTest.class.getResourceAsStream("/" + GOLDEN)) {
            assertThat(in).as("missing %s: run with -Pgolden.update=true and review the file", GOLDEN).isNotNull();
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
