package dev.abgleich.bootstrap;

import org.springframework.jdbc.core.JdbcTemplate;

/**
 * The stored outcome of a reconciliation as readable text: every payment with its allocations, then every
 * invoice. Nothing that differs between two identical runs (ids, timestamps, the import channel) appears in it.
 */
final class ReconciliationReport {

    private ReconciliationReport() {
    }

    static String render(JdbcTemplate jdbc) {
        StringBuilder out = new StringBuilder("# Example reconciliation. Synthetic data only.\n");
        out.append("# Generated by GoldenFileTest; review every change of this file.\n\n## Payments\n");
        jdbc.query("""
                select right(t.account_iban, 4) as account, t.booking_date, t.direction, t.amount, t.currency,
                       coalesce(t.counterparty_name, '-') as payer, coalesce(t.remittance_text, '-') as text,
                       coalesce(t.reference, '-') as reference, t.status,
                       coalesce(string_agg(i.invoice_number || ' ' || a.rule || ' ' || a.status
                                           || case when a.charges_written_off > 0
                                                   then ' charges ' || a.charges_written_off else '' end,
                                           ', ' order by i.invoice_number, a.status), '-') as allocations
                  from bank_transaction t
                  left join allocation a on a.transaction_id = t.id
                  left join invoice i on i.id = a.invoice_id
                 group by t.id
                 order by t.account_iban, t.booking_date, t.dedup_key
                """, rs -> {
            out.append(String.format("%s %s %-6s %s %10s | %s | %s | %s | %s -> %s%n",
                    rs.getString("account"), rs.getDate("booking_date").toLocalDate(), rs.getString("direction"),
                    rs.getString("currency"), rs.getBigDecimal("amount").toPlainString(), rs.getString("payer"),
                    rs.getString("text"), rs.getString("reference"), rs.getString("status"),
                    rs.getString("allocations")));
        });
        out.append("\n## Invoices\n");
        jdbc.query("select invoice_number, status, amount, paid_amount, currency from invoice order by invoice_number",
                rs -> {
                    out.append(String.format("%-13s %-15s %s %10s paid %10s%n", rs.getString("invoice_number"),
                            rs.getString("status"), rs.getString("currency"), rs.getBigDecimal("amount").toPlainString(),
                            rs.getBigDecimal("paid_amount").toPlainString()));
                });
        return out.toString();
    }
}
